Name: Tina LekshmiKanth
CWID: A20411284
Fall 18 - CS512

In [2]:
#B.2
import numpy as np
A = ([1,2,3],[4,-2,3],[0,5,-1])
B=([1,2,1],[2,1,-4],[3,-2,1])
AB= np.dot(A,B)
print(AB)

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]


In [3]:
BA = np.dot(B,A)
print(BA)

[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [5]:
#B.3
AB_Transpose = np.transpose(AB)
print(AB_Transpose)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [6]:
A_Trans= np.transpose(A)
B_Trans= np.transpose(B)
AtBt=np.dot(A_Trans,B_Trans)
print(AtBt)

[[  9   6  -5]
 [  3 -18  15]
 [  8  13   2]]


In [7]:
#B.6
from numpy.linalg import inv
A_Inv = inv(A)
print(A_Inv)
B_Inv = inv(B)
print(B_Inv)

[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [9]:
#C.1
AA = ([1,2],[3,2])
BB = ([2,-2], [-2, 5])
AA_EigenVals = np.linalg.eigvals(AA)
print(AA_EigenVals)


[-1.  4.]


In [11]:
AA_EigenVect = np.linalg.eig(AA)
print(AA_EigenVect)

(array([-1.,  4.]), array([[-0.70710678, -0.5547002 ],
       [ 0.70710678, -0.83205029]]))
